uploadHandler: 
  name: FullstackAsyncUploader-${self:provider.stage}
  handler: uploader/main.lambda_handler
  environment:
    QUEUE_URL:
      Fn::GetAtt:
        - WorkerBroker
        - QueueUrl
    BUCKET_NAME: ${self:provider.environment.ARTIFACTS_BUCKET}
  iamRoleStatements: 
  - Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
    Resource:
    - 'Fn::Join':
        - ':'
        - - 'arn:aws:logs'
          - Ref: 'AWS::Region'
          - Ref: 'AWS::AccountId'
          - 'log-group:/aws/lambda/*:*:*'
  - Effect: Allow
    Action: sqs:SendMessage
    Resource: !GetAtt WorkerBroker.Arn
  - Effect: Allow
    Action: s3:PutObject
    Resource: arn:aws:s3:::${self:provider.environment.ARTIFACTS_BUCKET}/*

  events:
    - http:
        method: get
        path: /api/upload
        cors: true