Resources:
  SocketRewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      AutoPublish: true 
      Name: FullstackAsyncCFRewriteWS
      FunctionConfig:
        Comment: Rewrite path for websocket 
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(e) {      
          var request = e.request;
    
          if (request.uri.includes('/socket')) {
            request.uri = '/dev';
          }
          return request;
        }

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: SocketRewriteFunction
    Properties:
       DistributionConfig:
        Origins:

          - Id: FrontendBucket
            DomainName: !Sub ${FrontendBucket}.s3.${AWS::Region}.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
  
          - Id: RestApi
            DomainName: 
              Fn::Join:
              - ""
              - - Ref: "ApiGatewayRestApi"
                - ".execute-api.${self:provider.region}.amazonaws.com"
            OriginPath: "/${self:provider.stage}"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

          - Id: WebSocket
            DomainName:
              Fn::Join:
              - ""
              - -  Ref: WebsocketsApi 
                - '.execute-api.${self:provider.region}.amazonaws.com'
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: FrontendBucket
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:

          - TargetOriginId: RestApi
            PathPattern: "api/*"
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac

          - TargetOriginId: WebSocket
            AllowedMethods: [GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE]
            PathPattern: "socket"
            FunctionAssociations:
              - EventType: 'viewer-request'
                FunctionARN: !GetAtt SocketRewriteFunction.FunctionMetadata.FunctionARN
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            ViewerProtocolPolicy: https-only

        Enabled: true
        DefaultRootObject: index.html    

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig: 
        Name: FullstackAsyncTestAcessControl
        OriginAccessControlOriginType: s3
        SigningBehavior: no-override
        SigningProtocol: sigv4
    