checkerHandler: 
  name: FullstackAsyncChecker-${self:provider.stage}
  handler: checker/main.lambda_handler
  environment:
    BUCKET_NAME: ${self:provider.environment.ARTIFACTS_BUCKET}
    WEBSOCKET_API:
      Fn::Join:
        - ''
        - - 'https://'
        # The following is an AWS variable Ref to the API Id 
          - Ref: WebsocketsApi
          - '.execute-api.'
          - Ref: AWS::Region
          - '.amazonaws.com/'
          - ${self:provider.stage}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
    Resource:
      - 'Fn::Join':
          - ':'
          - - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'log-group:/aws/lambda/*:*:*'
  - Effect: Allow
    Action: execute-api:ManageConnections
    Resource: arn:aws:execute-api:*:*:**/@connections/*
  - Effect: Allow
    Action:
      - s3:GetObject
      - s3:PutObject
      - s3:DeleteObject
      - s3:ListBucket
      - s3:HeadObject
    Resource: "*"
  - Effect: Allow
    Action: 
      - sqs:DeleteMessage
      - sqs:ReceiveMessage
      - sqs:GetQueueAttributes
    Resource: !GetAtt WorkerBroker.Arn
  events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
    - websocket:
        route: onCheck
